
name: "terraform chocolatey CI workflow"

on:
  push:
    branches: [ test ]


jobs:

  windows-latest-terraform:
    name: "windows-latest Microsoft Windows Server 2019 Datacenter terraform"  
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "Deploy terraform " 
      run: |
        choco install terraform
        terraform -help

  windows-2016-terraform:
    name: "Microsoft Windows Server 2016 Datacenter terraform"
    runs-on: windows-2016
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "Deploy terraform " 
      run: |
        choco install terraform
        terraform -help         
